name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.head_ref }} != "next" ] && [ ${{ github.base_ref }} == "main" ]; then
            printf '%s\n' "Test case x failed" >&2
            exit 1
          fi