name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.head_ref }} != "next" ] && [ ${{ github.base_ref }} == "main" ]; then
            echo "Pull requests to main are only allowed from next"
            exit 1
          fi
